services:
    zentrium_schedule.manager.availability:
        class: Zentrium\Bundle\ScheduleBundle\Entity\AvailabilityManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.requirement_set:
        class: Zentrium\Bundle\ScheduleBundle\Entity\RequirementSetManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.schedule:
        class: Zentrium\Bundle\ScheduleBundle\Entity\ScheduleManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.skill:
        class: Zentrium\Bundle\ScheduleBundle\Entity\SkillManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.shift:
        class: Zentrium\Bundle\ScheduleBundle\Entity\ShiftManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.task:
        class: Zentrium\Bundle\ScheduleBundle\Entity\TaskManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.user:
        class: Zentrium\Bundle\ScheduleBundle\Entity\UserManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.menu_listener:
        class: Zentrium\Bundle\ScheduleBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenu }
            - { name: kernel.event_listener, event: zentrium.menu.viewer, method: onCreateViewerMenu }

    zentrium_schedule.form.user_extension:
        class: Zentrium\Bundle\ScheduleBundle\Form\Extension\UserTypeExtension
        arguments: ["@zentrium_schedule.manager.user", "@router"]
        tags:
            - { name: form.type_extension, extended_type: Zentrium\Bundle\CoreBundle\Form\Type\UserType }
            - { name: kernel.event_listener, event: zentrium.user.edit.success, method: onSuccess }
