services:
    zentrium_schedule.manager.availability:
        class: Zentrium\Bundle\ScheduleBundle\Entity\AvailabilityManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.constraint:
        class: Zentrium\Bundle\ScheduleBundle\Entity\ConstraintManager
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer"]

    zentrium_schedule.manager.requirement_set:
        class: Zentrium\Bundle\ScheduleBundle\Entity\RequirementSetManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.schedule:
        class: Zentrium\Bundle\ScheduleBundle\Entity\ScheduleManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.skill:
        class: Zentrium\Bundle\ScheduleBundle\Entity\SkillManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.shift:
        class: Zentrium\Bundle\ScheduleBundle\Entity\ShiftManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.task:
        class: Zentrium\Bundle\ScheduleBundle\Entity\TaskManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.manager.user:
        class: Zentrium\Bundle\ScheduleBundle\Entity\UserManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium_schedule.menu_listener:
        class: Zentrium\Bundle\ScheduleBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenu }
            - { name: kernel.event_listener, event: zentrium.menu.viewer, method: onCreateViewerMenu }

    zentrium_schedule.form.user_extension:
        class: Zentrium\Bundle\ScheduleBundle\Form\Extension\UserTypeExtension
        arguments: ["@zentrium_schedule.manager.user", "@router"]
        tags:
            - { name: form.type_extension, extended_type: Zentrium\Bundle\CoreBundle\Form\Type\UserType }
            - { name: kernel.event_listener, event: zentrium.user.edit.success, method: onSuccess }

    zentrium_schedule.schedule.constraint_checker:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Checker
        arguments: ["@zentrium_schedule.schedule.constraint_registry"]

    zentrium_schedule.schedule.constraint_registry:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Registry

    zentrium_schedule.schedule.constraint.max_duration.builder:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Builder\MaxDurationBuilder
        arguments: ["@form.factory"]
        tags:
            - { name: zentrium_schedule.schedule.constraint_builder, type: max_duration }

    zentrium_schedule.schedule.constraint.max_duration.validator:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Validator\MaxDurationValidator
        arguments: ["@zentrium.templating.helper.duration", "@zentrium.templating.helper.datetime"]
        tags:
            - { name: zentrium_schedule.schedule.constraint_validator, type: max_duration }

    zentrium_schedule.schedule.constraint.skill.builder:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Builder\SkillBuilder
        tags:
            - { name: zentrium_schedule.schedule.constraint_builder, type: skill }

    zentrium_schedule.schedule.constraint.skill.validator:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Validator\SkillValidator
        arguments: ["@zentrium_schedule.manager.user", "@zentrium.templating.helper.duration"]
        tags:
            - { name: zentrium_schedule.schedule.constraint_validator, type: skill }

    zentrium_schedule.schedule.constraint.separation.builder:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Builder\SeparationBuilder
        tags:
            - { name: zentrium_schedule.schedule.constraint_builder, type: separation }

    zentrium_schedule.schedule.constraint.separation.validator:
        class: Zentrium\Bundle\ScheduleBundle\Schedule\Constraint\Validator\SeparationValidator
        tags:
            - { name: zentrium_schedule.schedule.constraint_validator, type: separation }
