imports:
    - { resource: version.php }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Container Configuration
parameters:
    container.autowiring.strict_mode: true
    container.dumper.inline_class_loader: true

# Zentrium Configuration
zentrium_core:
    default_country: "%country%"

# Framework Configuration
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_version: "%version%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            datetime: Zentrium\Bundle\CoreBundle\Doctrine\UtcDateTimeType
            json_deflate: Zentrium\Bundle\CoreBundle\Doctrine\JsonDeflateType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                hydrators:
                    column: Zentrium\Bundle\CoreBundle\Doctrine\ColumnHydrator

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: "%kernel.project_dir%/app/migrations"
    namespace: Zentrium\Migrations
    table_name: migration_versions
    name: Zentrium Migrations

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sortable: true
            timestampable: true

# FOSUser Configuration
fos_user:
    service:
        mailer: fos_user.mailer.twig_swift
    db_driver: orm
    firewall_name: main
    user_class: Zentrium\Bundle\CoreBundle\Entity\User
    group:
        group_class: Zentrium\Bundle\CoreBundle\Entity\Group
        form:
            type: Zentrium\Bundle\CoreBundle\Form\Type\GroupType
    from_email:
        address: "%mailer_from%"
        sender_name: Zentrium
    resetting:
        token_ttl: 3600
        email:
            template: ZentriumCoreBundle:Security:resetPassword.email.twig

# OAuth Server Configuration
fos_oauth_server:
    db_driver: orm
    client_class: Zentrium\Bundle\CoreBundle\Entity\Application
    access_token_class: Zentrium\Bundle\CoreBundle\Entity\AccessToken
    refresh_token_class: Zentrium\Bundle\CoreBundle\Entity\RefreshToken
    auth_code_class: Zentrium\Bundle\CoreBundle\Entity\AuthCode
    service:
        client_manager: zentrium.oauth_server.application_manager
        user_provider: fos_user.user_provider.username
        options:
            supported_scopes: map_position

# REST Configuration
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        enabled: true
        rules:
            - { path: ^/api/, fallback_format: json, prefer_extension: false }
            - { path: ^/, stop: true }
    exception:
        enabled: true
    view:
        view_response_listener:
            enabled: true

# PHP-HTTP Configuration
httplug:
    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        uri_factory: Http\Message\UriFactory\GuzzleUriFactory
        stream_factory: Http\Message\StreamFactory\GuzzleStreamFactory

# CSRF Protection Bundle
dunglas_angular_csrf:
    cookie:
        expire: 3600
        set_on:
            - { path: ^(?!/api/).*$, methods: [GET] }
    secure:
        - { route: _options }

# JS Translations Configuration
bazinga_js_translation:
    locale_fallback: "%locale%"
    default_domain: messages_js
    active_domains: [messages_js]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    port: "%mailer_port%"
    encryption: "%mailer_encryption%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }
