fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

api_auth_token:
    path: /api/auth/token
    defaults:  { _controller: fos_oauth_server.controller.token:tokenAction }
    methods: [GET, POST]

bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

core:
    resource: "@ZentriumCoreBundle/Controller/"
    type:     annotation

log:
    resource: "@ZentriumLogBundle/Controller/"
    type:     annotation

schedule:
    resource: "@ZentriumScheduleBundle/Controller/"
    type:     annotation

timesheet:
    resource: "@ZentriumTimesheetBundle/Controller/"
    type:     annotation

oaf:
    resource: "@VkafOafBundle/Controller/"
    type:     annotation
