fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

core:
    resource: "@ZentriumCoreBundle/Controller/"
    type:     annotation

log:
    resource: "@ZentriumLogBundle/Controller/"
    type:     annotation
