services:
    Aws\Sns\MessageValidator: ~

    Instasent\SMSCounter\SMSCounter: ~

    Vkaf\Bundle\OafBundle\:
        resource: "../../{Announcement,Command,Validator}/*"
        autowire: true
        autoconfigure: true
        public: false

    Vkaf\Bundle\OafBundle\Announcement\AwsMessenger:
        arguments:
            $senderId: "%vkaf_oaf.sms.sender_id%"
            $sendTopic: "%vkaf_oaf.sms.send_topic%"
            $statusTopic: "%vkaf_oaf.sms.status_topic%"
        autowire: true

    Vkaf\Bundle\OafBundle\Announcement\CostEstimator:
        arguments:
            $path: "%kernel.project_dir%/src/Vkaf/Bundle/OafBundle/Resources/config/sms_pricing.json"
        autowire: true

    Vkaf\Bundle\OafBundle\Announcement\MessengerInterface: '@Vkaf\Bundle\OafBundle\Announcement\AwsMessenger'

    Zentrium\Bundle\CoreBundle\Entity\UserRepository: '@zentrium.repository.user'

    vkaf_oaf.dashboard_listener:
        class: Vkaf\Bundle\OafBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@vkaf_oaf.lineup", "@zentrium_schedule.manager.schedule", "@vkaf_oaf.repository.shift", "@form.factory"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    vkaf_oaf.lineup:
        class: Vkaf\Bundle\OafBundle\Lineup\LineupManager
        arguments: ["%vkaf_oaf.lineup_path%"]

    vkaf_oaf.menu_listener:
        class: Vkaf\Bundle\OafBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenu }

    vkaf_oaf.manager.resource:
        class: Vkaf\Bundle\OafBundle\Entity\ResourceManager
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.manager.resource_assignment:
        class: Vkaf\Bundle\OafBundle\Entity\ResourceAssignmentManager
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.kiosk.slide_manager:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\SlideManager
        arguments: ["@templating"]

    vkaf_oaf.kiosk.slide.schedule:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\ScheduleSlide
        arguments: ["@zentrium_schedule.manager.shift", "@zentrium.repository.user"]
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: schedule }

    vkaf_oaf.kiosk.slide.schedule_list:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\ScheduleListSlide
        arguments: ["@zentrium_schedule.manager.shift", "@zentrium.repository.user"]
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: schedule_list }

    vkaf_oaf.kiosk.slide.welcome:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\WelcomeSlide
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: welcome }

    vkaf_oaf.pushpin:
        class: Vkaf\Bundle\OafBundle\Pushpin\GripPublisher
        arguments: ["@vkaf_oaf.pushpin.pub_control"]
        lazy: true

    vkaf_oaf.pushpin.param_converter:
        class: Vkaf\Bundle\OafBundle\Pushpin\GripParamConverter
        arguments: ["%vkaf_oaf.pushpin.key%"]
        tags:
            - { name: request.param_converter, converter: pushpin }

    vkaf_oaf.pushpin.pub_control:
        class: GripControl\GripPubControl
        arguments: [{"control_uri": "%vkaf_oaf.pushpin.api%"}]
        lazy: true

    vkaf_oaf.repository.kiosk:
        class: Vkaf\Bundle\OafBundle\Entity\KioskRepository
        factory: ["@doctrine", getRepository]
        arguments: [Vkaf\Bundle\OafBundle\Entity\Kiosk]

    vkaf_oaf.repository.shift:
        class: Vkaf\Bundle\OafBundle\Entity\ShiftRepository
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.repository.terminal:
        class: Vkaf\Bundle\OafBundle\Entity\TerminalRepository
        factory: ["@doctrine", getRepository]
        arguments: [Vkaf\Bundle\OafBundle\Entity\Terminal]

    vkaf_oaf.security.kiosk_authenticator:
        class: Vkaf\Bundle\OafBundle\Security\TokenAuthenticator
        arguments: ["@vkaf_oaf.repository.kiosk", "VkafOafBundle:Kiosk:unauthorized.html.twig", "@templating"]
        lazy: true

    vkaf_oaf.security.terminal_authenticator:
        class: Vkaf\Bundle\OafBundle\Security\TokenAuthenticator
        arguments: ["@vkaf_oaf.repository.terminal", "VkafOafBundle:Terminal:unauthorized.html.twig", "@templating"]
        lazy: true

    vkaf_oaf.terminals:
        class: Vkaf\Bundle\OafBundle\Terminal\TerminalManager
        arguments: ["@vkaf_oaf.pushpin", "@doctrine.orm.entity_manager", "@event_dispatcher", "%secret%"]
        lazy: true

    vkaf_oaf.timesheet.approvals:
        class: Vkaf\Bundle\OafBundle\Timesheet\ApprovalHandler
        arguments: ["@vkaf_oaf.pushpin", "@vkaf_oaf.terminals", "@doctrine.orm.entity_manager", "@validator", "@translator"]
        tags:
            - { name: kernel.event_listener, event: vkaf_oaf.terminal.flow, method: onFlowEvent }

    vkaf_oaf.timesheet.entry_listener:
        class: Vkaf\Bundle\OafBundle\Timesheet\EntryListener
        arguments: ["@router", "@translator"]
        tags:
            - { name: kernel.event_listener, event: zentrium_timesheet.entry.edit.completed, method: onEditCompleted }

    vkaf_oaf.twig.extension:
        class: Vkaf\Bundle\OafBundle\Twig\Extension
        arguments: ["%vkaf_oaf.pushpin.base_url%", "@router", "@translator"]
        tags:
            - { name: twig.extension }
