services:
    Minishlink\WebPush\WebPush:
        arguments:
            - VAPID:
                  subject: "%vkaf_oaf.push.subject%"
                  publicKey: "%vkaf_oaf.push.public_key%"
                  privateKey: "%vkaf_oaf.push.private_key%"
        calls:
            - [setAutomaticPadding, [0]] # web-push-libs/web-push-php#108

    Vkaf\Bundle\OafBundle\Command\:
        resource: "../../Command/*"
        autowire: true
        autoconfigure: true
        public: false

    Vkaf\Bundle\OafBundle\Push\PushManager:
        autowire: true

    vkaf_oaf.dashboard_listener:
        class: Vkaf\Bundle\OafBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@vkaf_oaf.lineup", "@form.factory"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    vkaf_oaf.lineup:
        class: Vkaf\Bundle\OafBundle\Lineup\LineupManager
        arguments: ["%vkaf_oaf.lineup_path%"]

    vkaf_oaf.menu_listener:
        class: Vkaf\Bundle\OafBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenu }

    vkaf_oaf.manager.resource:
        class: Vkaf\Bundle\OafBundle\Entity\ResourceManager
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.manager.resource_assignment:
        class: Vkaf\Bundle\OafBundle\Entity\ResourceAssignmentManager
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.kiosk.slide_manager:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\SlideManager
        arguments: ["@templating"]

    vkaf_oaf.kiosk.slide.schedule:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\ScheduleSlide
        arguments: ["@zentrium_schedule.manager.shift", "@zentrium.repository.user"]
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: schedule }

    vkaf_oaf.kiosk.slide.schedule_list:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\ScheduleListSlide
        arguments: ["@zentrium_schedule.manager.shift", "@zentrium.repository.user"]
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: schedule_list }

    vkaf_oaf.kiosk.slide.welcome:
        class: Vkaf\Bundle\OafBundle\Kiosk\Slide\WelcomeSlide
        tags:
            - { name: vkaf_oaf.kiosk.slide, type: welcome }

    vkaf_oaf.repository.shift:
        class: Vkaf\Bundle\OafBundle\Entity\ShiftRepository
        arguments: ["@doctrine.orm.entity_manager"]

    vkaf_oaf.security.kiosk_authenticator:
        class: Vkaf\Bundle\OafBundle\Security\KioskAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "@templating"]
        lazy: true

    vkaf_oaf.timesheet.entry_listener:
        class: Vkaf\Bundle\OafBundle\EventListener\TimesheetEntryListener
        arguments: ["@router", "@translator"]
        tags:
            - { name: kernel.event_listener, event: zentrium_timesheet.entry.edit.completed, method: onEditCompleted }

    vkaf_oaf.twig.extension:
        class: Vkaf\Bundle\OafBundle\Twig\Extension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }
