services:
    vkaf_oaf.dashboard_listener:
        class: Vkaf\Bundle\OafBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@vkaf_oaf.lineup", "@form.factory"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    vkaf_oaf.lineup:
        class: Vkaf\Bundle\OafBundle\Lineup\LineupManager
        arguments: ["%vkaf_oaf.lineup_path%"]

    vkaf_oaf.security.kiosk_authenticator:
        class: Vkaf\Bundle\OafBundle\Security\KioskAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "@templating"]
        lazy: true
