services:
    zentrium.dashboard.listener:
        class: Zentrium\Bundle\CoreBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@zentrium.repository.user"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    zentrium.menu.builder:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    zentrium.menu.listener:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuFirst, priority: 100 }
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuLast, priority: -100 }

    zentrium.repository.user:
        class: Zentrium\Bundle\CoreBundle\Entity\UserRepository
        factory: ["@doctrine", getRepository]
        arguments: [Zentrium\Bundle\CoreBundle\Entity\User]

    zentrium.twig.extension:
        class: Zentrium\Bundle\CoreBundle\Twig\Extension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension }
