services:
    zentrium.csrf.route_matcher:
        class: Zentrium\Bundle\CoreBundle\Csrf\RouteMatcher
        arguments: ["@router", _options]

    zentrium.dashboard.listener:
        class: Zentrium\Bundle\CoreBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@zentrium.repository.user"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    zentrium.oauth_server.application_manager:
        class: Zentrium\Bundle\CoreBundle\Entity\ApplicationManager
        arguments: ["@fos_oauth_server.entity_manager", %fos_oauth_server.model.client.class%]

    zentrium.menu.builder:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createViewerMenu, alias: viewer }

    zentrium.menu.listener:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuFirst, priority: 100 }
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuLast, priority: -100 }
            - { name: kernel.event_listener, event: zentrium.menu.viewer, method: onCreateViewerMenu, priority: -50 }

    zentrium.repository.user:
        class: Zentrium\Bundle\CoreBundle\Entity\UserRepository
        factory: ["@doctrine", getRepository]
        arguments: [Zentrium\Bundle\CoreBundle\Entity\User]

    zentrium.request.converter:
        class: Zentrium\Bundle\CoreBundle\Request\RequestBodyParamConverter
        arguments:
            - "@fos_rest.serializer"
            - %fos_rest.serializer.exclusion_strategy.groups%
            - %fos_rest.serializer.exclusion_strategy.version%
            - "@fos_rest.validator"
            - %fos_rest.converter.request_body.validation_errors_argument%
        tags:
            - { name: request.param_converter, converter: zentrium.request_body }

    zentrium.twig.extension:
        class: Zentrium\Bundle\CoreBundle\Twig\Extension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension }

    zentrium.view.validation_exception_listener:
        class: Zentrium\Bundle\CoreBundle\View\ValidationExceptionListener
        arguments: ["@fos_rest.exception_handler", "@fos_rest.view_handler"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
