services:
    zentrium.commonmark.environment:
        class: League\CommonMark\Environment
        factory: [League\CommonMark\Environment, createCommonMarkEnvironment]
        lazy: true
        calls:
            - [addDocumentProcessor, ["@zentrium.commonmark.processor.link"]]

    zentrium.commonmark.converter:
        class: League\CommonMark\CommonMarkConverter
        lazy: true
        arguments: [{ html_input: escape, allow_unsafe_links: false }, "@zentrium.commonmark.environment"]

    zentrium.commonmark.processor.link:
        class: Zentrium\Bundle\CoreBundle\CommonMark\LinkProcessor
        lazy: true

    zentrium.csrf.route_matcher:
        class: Zentrium\Bundle\CoreBundle\Csrf\RouteMatcher
        arguments: ["@router", _options]

    zentrium.dashboard.listener:
        class: Zentrium\Bundle\CoreBundle\Dashboard\DashboardListener
        arguments: ["@templating", "@zentrium.repository.user", "@zentrium.manager.text_widget", "@zentrium.commonmark.converter"]
        tags:
            - { name: kernel.event_listener, event: zentrium.dashboard, method: onBuildDashboard }

    zentrium.form.extension.change_password:
        class: Zentrium\Bundle\CoreBundle\Form\Extension\ChangePasswordTypeExtension
        tags:
            - { name: form.type_extension, extended_type: FOS\UserBundle\Form\Type\ChangePasswordFormType }

    zentrium.form.type.phone_number:
        class:  Zentrium\Bundle\CoreBundle\Form\Type\PhoneNumberType
        arguments: ["@libphonenumber.phone_number_util", "@zentrium.templating.helper.phone_number"]
        tags:
            - { name: form.type }

    zentrium.oauth_server.application_manager:
        class: Zentrium\Bundle\CoreBundle\Entity\ApplicationManager
        arguments: ["@fos_oauth_server.entity_manager", "%fos_oauth_server.model.client.class%"]

    zentrium.manager.text_widget:
        class: Zentrium\Bundle\CoreBundle\Entity\TextWidgetManager
        arguments: ["@doctrine.orm.entity_manager"]

    zentrium.menu.builder:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createViewerMenu, alias: viewer }

    zentrium.menu.listener:
        class: Zentrium\Bundle\CoreBundle\Menu\MenuListener
        tags:
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuFirst, priority: 100 }
            - { name: kernel.event_listener, event: zentrium.menu.main, method: onCreateMainMenuLast, priority: -100 }
            - { name: kernel.event_listener, event: zentrium.menu.viewer, method: onCreateViewerMenu, priority: -50 }

    zentrium.repository.user:
        class: Zentrium\Bundle\CoreBundle\Entity\UserRepository
        factory: ["@doctrine", getRepository]
        arguments: [Zentrium\Bundle\CoreBundle\Entity\User]

    zentrium.request.converter:
        class: Zentrium\Bundle\CoreBundle\Request\RequestBodyParamConverter
        arguments:
            - "@fos_rest.serializer"
            - "%fos_rest.serializer.exclusion_strategy.groups%"
            - "%fos_rest.serializer.exclusion_strategy.version%"
            - "@fos_rest.validator"
            - "%fos_rest.converter.request_body.validation_errors_argument%"
        tags:
            - { name: request.param_converter, converter: zentrium.request_body }

    zentrium.serializer.relation_handler:
        class: Zentrium\Bundle\CoreBundle\Serializer\RelationHandler
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: jms_serializer.handler, type: Relation, direction: serialization, format: json, method: serializeRelation }
            - { name: jms_serializer.handler, type: RelationCollection, direction: serialization, format: json, method: serializeRelationCollection }

    zentrium.templating.helper.duration:
        class: Zentrium\Bundle\CoreBundle\Templating\Helper\DurationHelper
        arguments: ["@translator"]
        public: false
        tags:
            - { name: templating.helper, alias: duration }

    zentrium.templating.helper.datetime:
        class: Zentrium\Bundle\CoreBundle\Templating\Helper\DateTimeHelper
        arguments: ["@sonata.intl.templating.helper.datetime", "@translator"]
        public: false
        tags:
            - { name: templating.helper, alias: datetime }

    zentrium.templating.helper.phone_number:
        class: Zentrium\Bundle\CoreBundle\Templating\Helper\PhoneNumberHelper
        arguments: ["@libphonenumber.phone_number_util", "%zentrium.default_country%"]
        public: false
        tags:
            - { name: templating.helper, alias: phone_number }

    zentrium.twig.extension:
        class: Zentrium\Bundle\CoreBundle\Twig\Extension
        arguments:
            - "@translator"
            - "@zentrium.templating.helper.phone_number"
            - "@zentrium.templating.helper.datetime"
            - "@zentrium.templating.helper.duration"
        public: false
        tags:
            - { name: twig.extension }

    zentrium.view.validation_exception_listener:
        class: Zentrium\Bundle\CoreBundle\View\ValidationExceptionListener
        arguments: ["@fos_rest.exception_handler", "@fos_rest.view_handler"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
