FOS\UserBundle\Model\User:
    properties:
        username:
            - NotBlank: ~
            - Regex: '/^[a-z0-9]+(\.[a-z0-9]+)*$/'
        email:
            - Length: { min: 2, max: 180, minMessage: fos_user.email.short, maxMessage: fos_user.email.long }
            - Email: { message: fos_user.email.invalid }
        plainPassword:
            - NotBlank: { message: fos_user.password.blank, groups: [Registration, ResetPassword, ChangePassword] }
            - Length: { min: 6, max: 100, minMessage: fos_user.password.short, groups: [Registration, Profile, ResetPassword, ChangePassword] }
